spring:
  application:
    name: zuul-server

server:
  port: 9100

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 8761
  instance:
    prefer-ip-address: true #在某些情况下，Eureka优先使用IP地址而不是主机名。设置为true，当应用程序向eureka注册时，它将使用其IP地址而不是其主机名
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: node1.eureka.com


management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  routes:
  # 这种方式配置路由规则：前面的key是微服务名称，后面是匹配路径
#    service-provider: /calcApi/**
    calc-proxy:
      serviceId: service-provider # 有效的微服务名称
      path: /calc/Api/**  # 访问路径
#  ignored-services: "*"
