spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: node1.eureka.com
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://node2.eureka.com:8762/eureka/,http://node3.eureka.com:8763/eureka/




server:
  port: 8761
---
spring:
  profiles: node2
server:
  port: 8762


eureka:
  instance:
    hostname: node2.eureka.com
  client:
    service-url:
      defaultZone: http://node1.eureka.com:8761/eureka/,http://node3.eureka.com:8763/eureka/


---
spring:
  profiles: node3
server:
  port: 8763


eureka:
  instance:
    hostname: node3.eureka.com
  client:
    service-url:
      defaultZone: http://node1.eureka.com:8761/eureka/,http://node2.eureka.com:8762/eureka/