server:
  port: 8761

spring:
  application:
    name: eureka-server


eureka:
  instance:
    hostname:  node1.eureka.com
    prefer-ip-address: true
  client:
    # 是否将当前应用注册到eureka中
    register-with-eureka: true
    # 是否从eureka注册中心中拉取服务提供者列表
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/